disabled_rules:
- identifier_name
- cyclomatic_complexity
- function_body_length
- line_length
- closure_parameter_position
- file_length
- type_body_length
- force_cast
- large_tuple
opt_in_rules:
- empty_count
- empty_string
excluded:
- Pods
- R.generated.swift
- Shared/Sources/Model/Protobuf